export const products = [
  {
    id: 1,
    title: "Z790 AORUS ELITE AX",
    price: 15000,
    stock: 2,
    description: "",
    category: "motherboard",
    img: "https://res.cloudinary.com/ds8t4shrj/image/upload/v1678472741/byteStore/motherboard_Z790_AORUS_ELITE_AX_ogd4ul.webp",
  },
  {
    id: 2,
    title: "ROG STRIX Z690-f Gaming Wifi",
    price: 14500,
    stock: 5,
    description: "",
    category: "motherboard",
    img: "https://res.cloudinary.com/ds8t4shrj/image/upload/v1678472716/byteStore/motherboard_rog_strix_z690-f_gaming_wifi_vqfzr4.jpg",
  },
  {
    id: 3,
    title: "MSI MPG b650 Carbon Wifi",
    price: 19000,
    stock: 5,
    description: "",
    category: "motherboards",
    img: "https://res.cloudinary.com/ds8t4shrj/image/upload/v1678473846/byteStore/msi-mpg-b650-carbon-wifi-2d-rgb_kkhmtf.jpg",
  },
  {
    id: 4,
    title: "AMD Ryzen 9 5900x",
    price: 17800,
    stock: 5,
    description: "",
    category: "procesador",
    img: "https://res.cloudinary.com/ds8t4shrj/image/upload/v1678472442/byteStore/amd_ryzen_9_5900x_ujjex3.webp",
  },
];
